# Generated by Django 5.2.6 on 2025-10-01 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('lng_OTP_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('str_Contact_Value', models.CharField(max_length=150)),
                ('str_OTP_Code', models.CharField(max_length=10)),
                ('dte_Sent_Time', models.DateTimeField()),
            ],
            options={
                'db_table': 'tbl_OTP_Verification',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('lng_User_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('str_Username', models.CharField(max_length=100)),
                ('str_Full_Name', models.CharField(max_length=200)),
                ('str_Hashed_Password', models.CharField(blank=True, max_length=255, null=True)),
                ('bln_IsPassword_Expiry', models.BooleanField()),
                ('dte_Last_Pwd_Modified_Date', models.DateTimeField(blank=True, null=True)),
                ('dte_Modified_Date', models.DateTimeField(blank=True, null=True)),
                ('dte_Created_Date', models.DateTimeField(auto_now_add=True)),
                ('dte_Last_Login', models.DateTimeField(blank=True, null=True)),
                ('bln_IsActive', models.BooleanField(default=True)),
                ('bln_IsDeleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tbl_User',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('lng_User_Address_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('str_Address_Line1', models.CharField(max_length=255)),
                ('str_Address_Line2', models.CharField(blank=True, max_length=255, null=True)),
                ('str_City', models.CharField(max_length=100)),
                ('str_State', models.CharField(max_length=100)),
                ('str_Country', models.CharField(max_length=100)),
                ('str_Zip_Code', models.CharField(max_length=20)),
                ('dte_Added_Date', models.DateTimeField()),
                ('bln_IsPrimary', models.BooleanField()),
                ('dte_Modified_Date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='lng_User_ID', on_delete=django.db.models.deletion.CASCADE, to='auth_user.user')),
            ],
            options={
                'db_table': 'tbl_User_Address',
            },
        ),
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('lng_User_ContactID', models.BigAutoField(primary_key=True, serialize=False)),
                ('str_Contact_Type', models.CharField(max_length=50)),
                ('str_Contact_Value', models.CharField(max_length=150)),
                ('bln_IsPrimary', models.BooleanField(blank=True, null=True)),
                ('bln_IsVerified', models.BooleanField()),
                ('dte_Verified_Date', models.DateTimeField(blank=True, null=True)),
                ('dte_Modified_Date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='lng_User_ID', on_delete=django.db.models.deletion.CASCADE, to='auth_user.user')),
            ],
            options={
                'db_table': 'tbl_User_Contact',
            },
        ),
        migrations.CreateModel(
            name='UserSSO',
            fields=[
                ('lng_User_SSO_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('str_SSO_Provider', models.CharField(max_length=50)),
                ('str_Provider_User_ID', models.CharField(max_length=200)),
                ('str_Email', models.CharField(max_length=150)),
                ('dte_Linked_Date', models.DateTimeField()),
                ('bln_IsActive', models.BooleanField(default=True)),
                ('dte_Modified_Date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='lng_User_ID', on_delete=django.db.models.deletion.CASCADE, to='auth_user.user')),
            ],
            options={
                'db_table': 'tbl_User_SSO',
            },
        ),
    ]
